export type ErrorCode =
  | 'CONTRACT_INVALID'
  | 'STATE_TRANSITION_INVALID'
  | 'RESEARCH_GATE_BLOCKED'
  | 'EVIDENCE_GATE_BLOCKED'
  | 'PRIVACY_GATE_BLOCKED'
  | 'PUBLISH_GATE_BLOCKED'
  | 'APPROVAL_STALE'
  | 'ARTIFACT_EXISTS'
  | 'ARTIFACT_NOT_FOUND'
  | 'WORKSPACE_PATH_INVALID'
  | 'CHARACTER_LIMIT_EXCEEDED'
  | 'BROWSER_EXECUTOR_UNAVAILABLE'
  | 'BROWSER_EXECUTOR_INCOMPATIBLE'
  | 'X_AUTH_REQUIRED'
  | 'X_ACCOUNT_MISMATCH'
  | 'X_SECURITY_CHALLENGE'
  | 'PAGE_CONTRACT_UNSUPPORTED'
  | 'DRAFT_CONFLICT'
  | 'REPLY_TARGET_STALE'
  | 'COMPOSER_ITEM_COUNT_MISMATCH'
  | 'COMPOSER_CONTENT_MISMATCH'
  | 'STALE_PAGE_REVISION'
  | 'COMMAND_REPLAY_REJECTED'
  | 'EXECUTION_BUSY'
  | 'SUBMIT_ALREADY_ATTEMPTED'
  | 'PUBLICATION_PARTIAL'
  | 'PUBLICATION_OUTCOME_UNKNOWN'
  | 'PUBLIC_VERIFICATION_CONFLICT'
  | 'UNSUPPORTED_PUBLICATION_FEATURE'
  | 'VISUAL_ASSET_INVALID'
  | 'VISUAL_FORMAT_UNSUPPORTED'
  | 'VISUAL_DIGEST_MISMATCH'
  | 'VISUAL_CLAIM_REF_INVALID'
  | 'VISUAL_SLOT_UNRESOLVED'
  | 'VISUAL_PATH_OUTSIDE_PACKAGE'
  | 'BROWSER_FILE_UPLOAD_UNAVAILABLE'
  | 'X_ATTACHMENT_CONFLICT'
  | 'X_ATTACHMENT_UPLOAD_FAILED'
  | 'X_ATTACHMENT_OUTCOME_UNKNOWN'
  | 'X_ATTACHMENT_MISMATCH'
  | 'X_ALT_TEXT_MISMATCH'
  | 'PUBLIC_MEDIA_UNVERIFIED'
  | 'ARTICLE_FORMAT_UNSUPPORTED'
  | 'ARTICLE_ASSET_MISMATCH'
  | 'ARTICLE_DRAFT_CONFLICT'
  | 'ARTICLE_PAGE_CONTRACT_UNSUPPORTED'
  | 'ARTICLE_CONTENT_MISMATCH'
  | 'ARTICLE_DRAFT_IDENTITY_UNKNOWN'
  | 'ARTICLE_PREVIEW_MISMATCH'
  | 'ARTICLE_PUBLICATION_CONFLICT'
  | 'ARTICLE_OUTCOME_UNKNOWN';

export class HarnessError extends Error {
  readonly code: ErrorCode;
  readonly details: unknown;

  constructor(code: ErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = 'HarnessError';
    this.code = code;
    this.details = details;
  }
}
